<?php
	//O PHP É UMA LINGUAGEM DE TIPAGEM DINAMICA POR COERÇÃO, OU  SEJA, O TIPO É DEFINIDO EM FUNÇÃO DO DADO QUE É ATRIBUÍDO.
	//DÁ-SE O NOME DE TYPECAST AO PROCESSO DE FORÇAR QUE DETERMINADA VARIÁVEL SEJA DE UM TIPO ESPECÍFICO.
	$n = 4;
	$no = "Carlos";

	//APLICANDO O TYPECAST
	$no1 = (int) "IVONILSON";

	echo $no1;

?>